name: Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Install Dependencies
      run: go mod download
      working-directory: ./server

    - name: Build Go server
      run: go build ./cmd/server/main.go
      working-directory: ./server

    - name: Run Go tests
      run: go test ./... -v
      working-directory: ./server
